[profile.default]
src = "src"
out = "abi"
libs = ["lib"]
remappings = [
    "@openzeppelin=lib/openzeppelin-contracts",
    "@morpho=lib/morpho-blue/src",
    "@morpho-public-allocator=lib/public-allocator/src"
]
fs_permissions = [{ access = "write", path = "../" }, { access = "read", path = "lib/morpho-blue/out" }]
solc_version = "0.8.30"
gas_reports = ["*"]
ffi = true
optimizer = true
optimizer_runs = 200
via_ir = true

additional_compiler_profiles = [{ name = "morpho", via_ir = false, solc_version = "0.8.19" }]
compilation_restrictions = [{ paths = "lib/morpho-blue/src/**", profile = "morpho" }]


[fuzz]
runs = 10000
seed = "0x1"

[invariant]
runs = 1000
depth = 500
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
